Automatic active space selection with SCINE autoCAS
goodchemistryco/Tangelo-Examples pull request #32
Opened 2023-11-23 17:29 UTC by AlexandreF-1qbit

Script to perform an active space search calculation with [SCINE autoCAS](https://github.com/qcscine/autocas/tree/master). The example shows an example with N2 / cc-pVDZ.

2023-11-23 21:46 UTC, JamesB-1qbit requested changes
Small docstring suggestions.

2023-11-23 21:46 UTC, JamesB-1qbit commented on examples/chemistry/autocas.py
> +    """Calls SCINE autoCAS to perform active space calculation on a molecule.
Calls SCINE autoCAS to generate the active space of a molecule

2023-11-23 21:46 UTC, JamesB-1qbit commented on examples/chemistry/autocas.py
> +    orbitals based on autoCAS results. Does not return any value.
Applies the active space obtained from autoCAS to the molecule.
Modifies the 'sqmol' object by in-place freezing molecular orbitals and utilizing the molecular
coefficients returned from autoCAS. Does not return any value.

2023-11-24 17:40 UTC, ValentinS4t1qbit commented on examples/chemistry/autocas.py
> +    print(n2)
Probably a good way to close is to state the molecule object is ready to be pushed in any classical or quantum solver.
Maybe we could run FCI on this to show the energy and state the AS has indeed been applied.

2023-11-28 16:09 UTC, ValentinS4t1qbit approved these changes

2023-11-28 16:10 UTC, merged